-- MySQL Script generated by MySQL Workbench
-- 09/20/17 02:23:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projetoirineu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetoirineu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetoirineu` DEFAULT CHARACTER SET latin1 ;
USE `projetoirineu` ;

-- -----------------------------------------------------
-- Table `projetoirineu`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`country` (
  `cdCountry` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome_country` VARCHAR(200) NOT NULL COMMENT '',
  `siglaCountry` VARCHAR(2) NOT NULL COMMENT '',
  `nacionalidade` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`cdCountry`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`estado` (
  `cdEstado` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome_estado` VARCHAR(200) NOT NULL COMMENT '',
  `siglaEstado` VARCHAR(2) NOT NULL COMMENT '',
  `cd_country` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`cdEstado`)  COMMENT '',
  INDEX `cd_country` (`cd_country` ASC)  COMMENT '',
  CONSTRAINT `estado_ibfk_1`
    FOREIGN KEY (`cd_country`)
    REFERENCES `projetoirineu`.`country` (`cdCountry`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`cidade` (
  `cdCidade` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome_cidade` VARCHAR(200) NOT NULL COMMENT '',
  `cd_estado` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`cdCidade`)  COMMENT '',
  INDEX `cd_estado` (`cd_estado` ASC)  COMMENT '',
  CONSTRAINT `cidade_ibfk_1`
    FOREIGN KEY (`cd_estado`)
    REFERENCES `projetoirineu`.`estado` (`cdEstado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`estadocivil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`estadocivil` (
  `cdEstadoCivil` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao_ec` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`cdEstadoCivil`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`pessoa` (
  `cdPessoa` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(200) NOT NULL COMMENT '',
  `data_nasc` DATE NOT NULL COMMENT '',
  `sexo` VARCHAR(20) NOT NULL COMMENT '',
  `RG` INT(11) NOT NULL COMMENT '',
  `CPF` VARCHAR(20) NOT NULL COMMENT '',
  `passaporte` VARCHAR(200) NULL DEFAULT NULL COMMENT '',
  `nome_pai` VARCHAR(200) NOT NULL COMMENT '',
  `nome_mae` VARCHAR(200) NOT NULL COMMENT '',
  `ativo` TINYINT(1) NOT NULL COMMENT '',
  `cd_est_civil` INT(11) NULL DEFAULT NULL COMMENT '',
  `cd_naturalidade` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`cdPessoa`)  COMMENT '',
  UNIQUE INDEX `CPF` (`CPF` ASC)  COMMENT '',
  INDEX `cd_est_civil` (`cd_est_civil` ASC)  COMMENT '',
  INDEX `cd_naturalidade` (`cd_naturalidade` ASC)  COMMENT '',
  CONSTRAINT `pessoa_ibfk_1`
    FOREIGN KEY (`cd_est_civil`)
    REFERENCES `projetoirineu`.`estadocivil` (`cdEstadoCivil`),
  CONSTRAINT `pessoa_ibfk_2`
    FOREIGN KEY (`cd_naturalidade`)
    REFERENCES `projetoirineu`.`cidade` (`cdCidade`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`taxa_inscricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`taxa_inscricao` (
  `cdTaxaInscricao` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `data_vencimento_boleto` DATE NOT NULL COMMENT '',
  `taxa_inscricao` DECIMAL(6,2) NULL DEFAULT NULL COMMENT '',
  `pago` TINYINT(1) NOT NULL COMMENT '',
  `data_pagamento` DATE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`cdTaxaInscricao`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`tipo_processo_seletivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`tipo_processo_seletivo` (
  `cdTipoProcesso` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(200) NOT NULL COMMENT '',
  `cd_taxa_inscricao` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`cdTipoProcesso`)  COMMENT '',
  INDEX `cd_taxa_inscricao` (`cd_taxa_inscricao` ASC)  COMMENT '',
  CONSTRAINT `tipo_processo_seletivo_ibfk_1`
    FOREIGN KEY (`cd_taxa_inscricao`)
    REFERENCES `projetoirineu`.`taxa_inscricao` (`cdTaxaInscricao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`processo_seletivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`processo_seletivo` (
  `cdProcessoSeletivo` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `data_inicio` DATE NOT NULL COMMENT '',
  `data_fim` DATE NOT NULL COMMENT '',
  `cd_tipo_processo` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`cdProcessoSeletivo`)  COMMENT '',
  INDEX `cd_tipo_processo` (`cd_tipo_processo` ASC)  COMMENT '',
  CONSTRAINT `processo_seletivo_ibfk_1`
    FOREIGN KEY (`cd_tipo_processo`)
    REFERENCES `projetoirineu`.`tipo_processo_seletivo` (`cdTipoProcesso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`comissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`comissao` (
  `cdComissao` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(200) NOT NULL COMMENT '',
  `cd_pessoa` INT(11) NOT NULL COMMENT '',
  `cd_processo_seletivo` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`cdComissao`)  COMMENT '',
  INDEX `cd_pessoa` (`cd_pessoa` ASC)  COMMENT '',
  INDEX `cd_processo_seletivo` (`cd_processo_seletivo` ASC)  COMMENT '',
  CONSTRAINT `comissao_ibfk_1`
    FOREIGN KEY (`cd_pessoa`)
    REFERENCES `projetoirineu`.`pessoa` (`cdPessoa`),
  CONSTRAINT `comissao_ibfk_2`
    FOREIGN KEY (`cd_processo_seletivo`)
    REFERENCES `projetoirineu`.`processo_seletivo` (`cdProcessoSeletivo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`cota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`cota` (
  `cdCota` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(200) NOT NULL COMMENT '',
  PRIMARY KEY (`cdCota`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`curso` (
  `cdCurso` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome_curso` VARCHAR(200) NOT NULL COMMENT '',
  PRIMARY KEY (`cdCurso`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`tipo_deficiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`tipo_deficiencia` (
  `cdTipoDeficiencia` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(200) NOT NULL COMMENT '',
  PRIMARY KEY (`cdTipoDeficiencia`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`deficiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`deficiencia` (
  `cdDeficiencia` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo` TINYINT(1) NOT NULL COMMENT '',
  `observacoes` VARCHAR(200) NOT NULL COMMENT '',
  `cd_tipo_deficiencia` INT(11) NOT NULL COMMENT '',
  `cd_pessoa` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`cdDeficiencia`)  COMMENT '',
  INDEX `cd_tipo_deficiencia` (`cd_tipo_deficiencia` ASC)  COMMENT '',
  INDEX `cd_pessoa` (`cd_pessoa` ASC)  COMMENT '',
  CONSTRAINT `deficiencia_ibfk_1`
    FOREIGN KEY (`cd_tipo_deficiencia`)
    REFERENCES `projetoirineu`.`tipo_deficiencia` (`cdTipoDeficiencia`),
  CONSTRAINT `deficiencia_ibfk_2`
    FOREIGN KEY (`cd_pessoa`)
    REFERENCES `projetoirineu`.`pessoa` (`cdPessoa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`emissor_rg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`emissor_rg` (
  `cd_pessoa` INT(11) NOT NULL COMMENT '',
  `emissor_rg` VARCHAR(30) NOT NULL COMMENT '',
  PRIMARY KEY (`cd_pessoa`)  COMMENT '',
  CONSTRAINT `emissor_rg_ibfk_1`
    FOREIGN KEY (`cd_pessoa`)
    REFERENCES `projetoirineu`.`pessoa` (`cdPessoa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`endereco` (
  `cdEndereco` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `cep` INT(11) NOT NULL COMMENT '',
  `rua` VARCHAR(200) NOT NULL COMMENT '',
  `numero` INT(11) NOT NULL COMMENT '',
  `bairro` VARCHAR(100) NOT NULL COMMENT '',
  `cd_cidade` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`cdEndereco`)  COMMENT '',
  INDEX `cd_cidade` (`cd_cidade` ASC)  COMMENT '',
  CONSTRAINT `endereco_ibfk_1`
    FOREIGN KEY (`cd_cidade`)
    REFERENCES `projetoirineu`.`cidade` (`cdCidade`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`escolaridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`escolaridade` (
  `cdEscolaridade` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(200) NOT NULL COMMENT '',
  PRIMARY KEY (`cdEscolaridade`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`inscricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`inscricao` (
  `cdInscricao` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `data_inscricao` DATE NOT NULL COMMENT '',
  `primeira_opcurso` INT(11) NOT NULL COMMENT '',
  `segunda_opcurso` INT(11) NULL DEFAULT NULL COMMENT '',
  `cd_processo_seletivo` INT(11) NOT NULL COMMENT '',
  `cd_pessoa` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`cdInscricao`)  COMMENT '',
  INDEX `primeira_opcurso` (`primeira_opcurso` ASC)  COMMENT '',
  INDEX `segunda_opcurso` (`segunda_opcurso` ASC)  COMMENT '',
  INDEX `cd_pessoa` (`cd_pessoa` ASC)  COMMENT '',
  INDEX `cd_processo_seletivo` (`cd_processo_seletivo` ASC)  COMMENT '',
  CONSTRAINT `inscricao_ibfk_1`
    FOREIGN KEY (`primeira_opcurso`)
    REFERENCES `projetoirineu`.`curso` (`cdCurso`),
  CONSTRAINT `inscricao_ibfk_2`
    FOREIGN KEY (`segunda_opcurso`)
    REFERENCES `projetoirineu`.`curso` (`cdCurso`),
  CONSTRAINT `inscricao_ibfk_3`
    FOREIGN KEY (`cd_pessoa`)
    REFERENCES `projetoirineu`.`pessoa` (`cdPessoa`),
  CONSTRAINT `inscricao_ibfk_4`
    FOREIGN KEY (`cd_processo_seletivo`)
    REFERENCES `projetoirineu`.`processo_seletivo` (`cdProcessoSeletivo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`inscricao_cotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`inscricao_cotas` (
  `cdInscricaoCotas` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `cd_inscricao` INT(11) NOT NULL COMMENT '',
  `cd_cota` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`cdInscricaoCotas`)  COMMENT '',
  INDEX `cd_inscricao` (`cd_inscricao` ASC)  COMMENT '',
  INDEX `cd_cota` (`cd_cota` ASC)  COMMENT '',
  CONSTRAINT `inscricao_cotas_ibfk_1`
    FOREIGN KEY (`cd_inscricao`)
    REFERENCES `projetoirineu`.`inscricao` (`cdInscricao`),
  CONSTRAINT `inscricao_cotas_ibfk_2`
    FOREIGN KEY (`cd_cota`)
    REFERENCES `projetoirineu`.`cota` (`cdCota`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`isencao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`isencao` (
  `cdIsencao` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `motivo` TEXT NOT NULL COMMENT '',
  `homologada` TINYINT(1) NOT NULL COMMENT '',
  `cd_inscricao` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`cdIsencao`)  COMMENT '',
  INDEX `cd_inscricao` (`cd_inscricao` ASC)  COMMENT '',
  CONSTRAINT `isencao_ibfk_1`
    FOREIGN KEY (`cd_inscricao`)
    REFERENCES `projetoirineu`.`inscricao` (`cdInscricao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`tipo_notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`tipo_notificacao` (
  `cdTipoNotificacao` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(200) NOT NULL COMMENT '',
  PRIMARY KEY (`cdTipoNotificacao`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`notificacao` (
  `cdNotificacao` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `cd_tipo_notificacao` INT(11) NOT NULL COMMENT '',
  `cd_pessoa` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`cdNotificacao`)  COMMENT '',
  INDEX `cd_tipo_notificacao` (`cd_tipo_notificacao` ASC)  COMMENT '',
  INDEX `cd_pessoa` (`cd_pessoa` ASC)  COMMENT '',
  CONSTRAINT `notificacao_ibfk_1`
    FOREIGN KEY (`cd_tipo_notificacao`)
    REFERENCES `projetoirineu`.`tipo_notificacao` (`cdTipoNotificacao`),
  CONSTRAINT `notificacao_ibfk_2`
    FOREIGN KEY (`cd_pessoa`)
    REFERENCES `projetoirineu`.`pessoa` (`cdPessoa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`processo_seletivo_cota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`processo_seletivo_cota` (
  `cdProcessoSeletivoCota` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `vagas` INT(11) NOT NULL COMMENT '',
  `cd_processo_seletivo` INT(11) NOT NULL COMMENT '',
  `cd_cotas` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`cdProcessoSeletivoCota`)  COMMENT '',
  INDEX `cd_processo_seletivo` (`cd_processo_seletivo` ASC)  COMMENT '',
  INDEX `cd_cotas` (`cd_cotas` ASC)  COMMENT '',
  CONSTRAINT `processo_seletivo_cota_ibfk_1`
    FOREIGN KEY (`cd_processo_seletivo`)
    REFERENCES `projetoirineu`.`processo_seletivo` (`cdProcessoSeletivo`),
  CONSTRAINT `processo_seletivo_cota_ibfk_2`
    FOREIGN KEY (`cd_cotas`)
    REFERENCES `projetoirineu`.`cota` (`cdCota`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`telefone` (
  `cdTelefone` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `telefone` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`cdTelefone`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`tipo_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`tipo_endereco` (
  `cdTipoEndereco` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(100) NOT NULL COMMENT '',
  `cd_pessoa` INT(11) NOT NULL COMMENT '',
  `cd_endereco` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`cdTipoEndereco`)  COMMENT '',
  INDEX `cd_pessoa` (`cd_pessoa` ASC)  COMMENT '',
  INDEX `cd_endereco` (`cd_endereco` ASC)  COMMENT '',
  CONSTRAINT `tipo_endereco_ibfk_1`
    FOREIGN KEY (`cd_pessoa`)
    REFERENCES `projetoirineu`.`pessoa` (`cdPessoa`),
  CONSTRAINT `tipo_endereco_ibfk_2`
    FOREIGN KEY (`cd_endereco`)
    REFERENCES `projetoirineu`.`endereco` (`cdEndereco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`tipo_escolaridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`tipo_escolaridade` (
  `cdTipoEscolaridade` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(100) NOT NULL COMMENT '',
  `cd_pessoa` INT(11) NOT NULL COMMENT '',
  `cd_escolaridade` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`cdTipoEscolaridade`)  COMMENT '',
  INDEX `cd_pessoa` (`cd_pessoa` ASC)  COMMENT '',
  INDEX `cd_escolaridade` (`cd_escolaridade` ASC)  COMMENT '',
  CONSTRAINT `tipo_escolaridade_ibfk_1`
    FOREIGN KEY (`cd_pessoa`)
    REFERENCES `projetoirineu`.`pessoa` (`cdPessoa`),
  CONSTRAINT `tipo_escolaridade_ibfk_2`
    FOREIGN KEY (`cd_escolaridade`)
    REFERENCES `projetoirineu`.`escolaridade` (`cdEscolaridade`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`tipo_telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`tipo_telefone` (
  `cdTipoTelefone` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(100) NOT NULL COMMENT '',
  `cd_pessoa` INT(11) NOT NULL COMMENT '',
  `cd_telefone` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`cdTipoTelefone`)  COMMENT '',
  INDEX `cd_pessoa` (`cd_pessoa` ASC)  COMMENT '',
  INDEX `cd_telefone` (`cd_telefone` ASC)  COMMENT '',
  CONSTRAINT `tipo_telefone_ibfk_1`
    FOREIGN KEY (`cd_pessoa`)
    REFERENCES `projetoirineu`.`pessoa` (`cdPessoa`),
  CONSTRAINT `tipo_telefone_ibfk_2`
    FOREIGN KEY (`cd_telefone`)
    REFERENCES `projetoirineu`.`telefone` (`cdTelefone`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetoirineu`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoirineu`.`usuario` (
  `cd_pessoa` INT(11) NOT NULL COMMENT '',
  `usuario` VARCHAR(100) NOT NULL COMMENT '',
  `senha` VARCHAR(50) NOT NULL COMMENT '',
  `email` VARCHAR(100) NOT NULL COMMENT '',
  `tipo` VARCHAR(50) NOT NULL COMMENT '',
  `data_cad` DATE NOT NULL COMMENT '',
  `data_last_update` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`cd_pessoa`)  COMMENT '',
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`cd_pessoa`)
    REFERENCES `projetoirineu`.`pessoa` (`cdPessoa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
